In [1]:
import pandas as pd
import numpy as np

# Read the data from the CSV file
df = pd.read_csv('./Delhi_sep_No2.csv')
df

,longitude,latitude,2023-09-01,2023-09-02,2023-09-03,2023-09-04,2023-09-05,2023-09-06,2023-09-07,2023-09-08,...,2023-09-20,2023-09-21,2023-09-22,2023-09-23,2023-09-24,2023-09-25,2023-09-27,2023-09-28,2023-09-29,2023-09-30
0,76.832916,28.408461,NaN,0.000042,0.000013,7.851221e-07,1.598339e-05,0.000030,0.000015,5.162810e-06,...,0.000009,0.000040,0.000099,0.000013,0.000020,9.742981e-07,0.000011,0.000017,0.000005,8.061776e-06
1,76.832916,28.422062,NaN,0.000030,0.000012,1.135144e-05,NaN,0.000030,0.000008,-2.578716e-06,...,-0.000031,NaN,0.000009,0.000011,0.000025,3.139571e-05,0.000016,0.000002,NaN,-1.252726e-06
2,76.832916,28.435664,0.000001,0.000036,-0.000044,NaN,1.187287e-05,0.000010,0.000033,NaN,...,NaN,-0.000009,0.000016,0.000010,0.000043,1.960827e-05,0.000004,0.000012,0.000023,1.663727e-05
3,76.832916,28.449265,0.000008,0.000011,0.000012,NaN,1.214876e-06,0.000025,0.000018,-1.419294e-06,...,NaN,0.000003,0.000014,0.000010,0.000029,2.302066e-05,0.000002,0.000008,0.000032,2.134110e-05
4,76.832916,28.462866,NaN,0.000030,0.000015,-1.324731e-05,5.431245e-06,0.000012,0.000014,8.967905e-06,...,0.000011,-0.000005,-0.000021,0.000011,0.000027,2.190603e-05,0.000007,0.000009,0.000024,7.714142e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1363,77.328716,28.830106,0.000025,0.000022,0.000008,-1.005415e-05,-9.851082e-07,0.000023,NaN,5.685288e-06,...,0.000080,0.000017,0.000006,0.000012,0.000015,1.637433e-05,0.000009,0.000012,0.000041,1.117320e-05
1364,77.328716,28.843708,0.000016,0.000018,0.000020,9.390858e-06,NaN,0.000022,NaN,NaN,...,0.000011,0.000018,-0.000001,0.000032,0.000010,1.474426e-05,0.000010,0.000002,0.000021,4.456878e-05
1365,77.328716,28.857309,NaN,NaN,-0.000016,4.749173e-06,1.206551e-05,0.000012,NaN,1.781609e-05,...,0.000025,0.000007,0.000069,0.000027,0.000020,3.130691e-06,0.000018,0.000010,0.000011,9.013133e-06
1366,77.328716,28.870910,0.000012,NaN,0.000027,NaN,1.423883e-05,0.000007,NaN,-2.199187e-06,...,0.000010,NaN,0.000070,0.000006,0.000014,NaN,0.000009,-0.000001,0.000026,6.785802e-05
1367,77.328716,28.884512,0.000027,0.000029,NaN,-3.002178e-07,NaN,0.000009,0.000263,9.106080e-08,...,0.000002,0.000010,0.000011,0.000010,0.000010,1.365496e-06,0.000002,0.000027,0.000018,-3.818894e-07

In [2]:
# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    print(f"Mean for {column}: {mean_value}")

Mean for 2023-09-01: 2.0566232768439664e-05
Mean for 2023-09-02: 2.520870802405591e-05
Mean for 2023-09-03: 1.8487483034906315e-05
Mean for 2023-09-04: 4.579174279590711e-06
Mean for 2023-09-05: 1.763529953521991e-05
Mean for 2023-09-06: 2.09294897948501e-05
Mean for 2023-09-07: 2.288934195842215e-05
Mean for 2023-09-08: 1.6709824006455936e-06
Mean for 2023-09-09: 4.790690425888591e-06
Mean for 2023-09-10: 2.04753269615152e-05
Mean for 2023-09-11: 1.365987867028749e-05
Mean for 2023-09-12: 2.0822729682936295e-05
Mean for 2023-09-13: 7.87746126517064e-06
Mean for 2023-09-14: 1.1103507057462006e-05
Mean for 2023-09-15: 2.414073628523319e-05
Mean for 2023-09-16: 1.668714960791677e-05
Mean for 2023-09-17: 7.1354096603341556e-06
Mean for 2023-09-18: 7.048810302356791e-06
Mean for 2023-09-19: 2.4439061356426956e-05
Mean for 2023-09-20: 2.1949250153906567e-05
Mean for 2023-09-21: 2.3554157610126043e-05
Mean for 2023-09-22: 1.5462653142784234e-05
Mean for 2023-09-23: 3.832313678574653e-05
Mean for 2023-09-24: 2.5962263318215688e-05
Mean for 2023-09-25: 1.6013550444765232e-05
Mean for 2023-09-27: 1.6072435522425613e-05
Mean for 2023-09-28: 1.2577863016521963e-05
Mean for 2023-09-29: 2.1695736483166694e-05
Mean for 2023-09-30: 1.6302362774252333e-05

In [3]:
import pandas as pd
import numpy as np

# Create a new DataFrame to store the results
result_df = pd.DataFrame(columns=['date', 'threshold_value'])

# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    result_df = pd.concat([result_df, pd.DataFrame({'date': [column], 'threshold_value': [mean_value]})], ignore_index=True)

# Print or display the resulting DataFrame
print(result_df)

          date  threshold_value
0   2023-09-01         0.000021
1   2023-09-02         0.000025
2   2023-09-03         0.000018
3   2023-09-04         0.000005
4   2023-09-05         0.000018
5   2023-09-06         0.000021
6   2023-09-07         0.000023
7   2023-09-08         0.000002
8   2023-09-09         0.000005
9   2023-09-10         0.000020
10  2023-09-11         0.000014
11  2023-09-12         0.000021
12  2023-09-13         0.000008
13  2023-09-14         0.000011
14  2023-09-15         0.000024
15  2023-09-16         0.000017
16  2023-09-17         0.000007
17  2023-09-18         0.000007
18  2023-09-19         0.000024
19  2023-09-20         0.000022
20  2023-09-21         0.000024
21  2023-09-22         0.000015
22  2023-09-23         0.000038
23  2023-09-24         0.000026
24  2023-09-25         0.000016
25  2023-09-27         0.000016
26  2023-09-28         0.000013
27  2023-09-29         0.000022
28  2023-09-30         0.000016

In [4]:
#thresold value csv file

In [5]:
# Save the resulting DataFrame to a CSV file
result_df.to_csv('./threshold_value_delhi_sep_no2.csv', index=False)