In [1]:
import pandas as pd
import numpy as np

# Read the data from the CSV file
df = pd.read_csv('./karnataka_sep_No2.csv')
df

,longitude,latitude,2023-09-01,2023-09-02,2023-09-03,2023-09-04,2023-09-05,2023-09-06,2023-09-07,2023-09-08,...,2023-09-20,2023-09-21,2023-09-22,2023-09-23,2023-09-24,2023-09-25,2023-09-27,2023-09-28,2023-09-29,2023-09-30
0,74.054306,11.574480,NaN,NaN,NaN,NaN,2.267027e-06,0.000034,0.000010,0.000006,...,6.530644e-06,6.636121e-06,-0.000006,7.756475e-06,0.000014,1.667625e-05,-0.000002,-8.464654e-07,2.758478e-05,0.000020
1,74.054306,11.714901,NaN,0.000009,0.000009,0.000010,8.894076e-06,-0.000002,-0.000012,-0.000001,...,1.397371e-05,1.785967e-05,0.000004,1.647706e-05,0.000009,1.254908e-05,0.000004,6.742497e-06,4.419413e-05,0.000024
2,74.054306,11.855323,NaN,0.000018,0.000041,-0.000006,8.526424e-06,0.000022,0.000002,-0.000004,...,1.827239e-05,9.557136e-07,0.000015,3.540752e-07,0.000020,8.561604e-06,0.000010,4.703154e-06,1.283822e-05,0.000027
3,74.054306,11.995744,0.000002,0.000011,NaN,0.000002,-5.087257e-06,0.000018,0.000019,0.000002,...,5.800705e-07,1.082250e-06,0.000003,1.073900e-05,-0.000002,1.202443e-05,0.000015,-5.860704e-06,5.501217e-06,0.000014
4,74.054306,12.136165,0.000004,0.000007,NaN,-0.000012,4.072991e-06,0.000005,-0.000011,0.000007,...,1.104900e-05,5.016641e-06,-0.000008,2.384833e-06,0.000011,5.814975e-06,0.000008,1.583956e-05,3.010925e-05,0.000028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,78.534306,17.893435,0.000026,0.000008,0.000009,0.000002,1.919875e-05,0.000020,0.000020,NaN,...,1.253222e-05,7.740547e-06,-0.000006,3.032113e-05,0.000010,2.200709e-05,0.000009,-3.495059e-08,7.650494e-07,0.000011
1646,78.534306,18.033856,0.000019,0.000032,NaN,0.000019,1.131414e-06,0.000013,0.000025,0.000005,...,2.449177e-05,4.964715e-06,0.000006,1.799283e-05,0.000029,1.032282e-05,0.000010,2.277078e-06,8.138777e-06,0.000015
1647,78.534306,18.174278,0.000013,0.000089,0.000020,0.000011,2.970559e-07,0.000031,NaN,0.000004,...,2.569296e-05,3.491830e-06,0.000007,1.974484e-07,0.000017,8.705461e-07,0.000014,8.126046e-06,4.089115e-06,0.000020
1648,78.534306,18.314699,NaN,0.000021,NaN,0.000004,1.717001e-05,0.000036,0.000009,NaN,...,6.980406e-06,1.539497e-05,0.000012,9.940867e-06,0.000011,5.009822e-05,0.000029,1.889884e-05,6.186346e-06,0.000019
1649,78.534306,18.455120,0.000014,0.000020,0.000020,0.000011,1.462506e-05,0.000011,0.000035,0.000023,...,1.775559e-05,1.185199e-05,-0.000001,6.277153e-06,0.000093,2.694557e-05,0.000034,4.662231e-06,2.658908e-05,0.000056

In [2]:
# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    print(f"Mean for {column}: {mean_value}")

Mean for 2023-09-01: 1.6636943435180565e-05
Mean for 2023-09-02: 1.534779829738958e-05
Mean for 2023-09-03: 2.8363516987058634e-05
Mean for 2023-09-04: 5.287814814744062e-06
Mean for 2023-09-05: 1.4025744820399244e-06
Mean for 2023-09-06: 1.9424192563242836e-05
Mean for 2023-09-07: 1.3818242507561865e-05
Mean for 2023-09-08: 7.377554683625163e-06
Mean for 2023-09-09: 8.614233954215409e-06
Mean for 2023-09-10: 2.3513064337190093e-05
Mean for 2023-09-11: 4.477881031515973e-06
Mean for 2023-09-12: 1.5253218987636657e-05
Mean for 2023-09-13: 6.1727568877007135e-06
Mean for 2023-09-14: 2.1507682709191025e-05
Mean for 2023-09-15: 7.132103096990137e-06
Mean for 2023-09-16: 1.8197721762588453e-05
Mean for 2023-09-17: 4.561341550227888e-06
Mean for 2023-09-18: 6.625765125746922e-06
Mean for 2023-09-19: 1.2157755271221555e-05
Mean for 2023-09-20: 9.318373411262146e-06
Mean for 2023-09-21: 6.0337086534827235e-06
Mean for 2023-09-22: 5.603377877015456e-06
Mean for 2023-09-23: 1.3910015175311891e-05
Mean for 2023-09-24: 1.2404122356111036e-05
Mean for 2023-09-25: 2.378788341068822e-05
Mean for 2023-09-27: 2.0121434376971308e-05
Mean for 2023-09-28: 6.64999547148232e-06
Mean for 2023-09-29: 2.0425973830189155e-05
Mean for 2023-09-30: 2.7089851625293195e-05

In [3]:
import pandas as pd
import numpy as np

# Create a new DataFrame to store the results
result_df = pd.DataFrame(columns=['date', 'threshold_value'])

# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    result_df = pd.concat([result_df, pd.DataFrame({'date': [column], 'threshold_value': [mean_value]})], ignore_index=True)

# Print or display the resulting DataFrame
print(result_df)

          date  threshold_value
0   2023-09-01         0.000017
1   2023-09-02         0.000015
2   2023-09-03         0.000028
3   2023-09-04         0.000005
4   2023-09-05         0.000001
5   2023-09-06         0.000019
6   2023-09-07         0.000014
7   2023-09-08         0.000007
8   2023-09-09         0.000009
9   2023-09-10         0.000024
10  2023-09-11         0.000004
11  2023-09-12         0.000015
12  2023-09-13         0.000006
13  2023-09-14         0.000022
14  2023-09-15         0.000007
15  2023-09-16         0.000018
16  2023-09-17         0.000005
17  2023-09-18         0.000007
18  2023-09-19         0.000012
19  2023-09-20         0.000009
20  2023-09-21         0.000006
21  2023-09-22         0.000006
22  2023-09-23         0.000014
23  2023-09-24         0.000012
24  2023-09-25         0.000024
25  2023-09-27         0.000020
26  2023-09-28         0.000007
27  2023-09-29         0.000020
28  2023-09-30         0.000027

In [4]:
#thresold value csv file

In [4]:
# Save the resulting DataFrame to a CSV file
result_df.to_csv('./threshold_value_karnataka_sep_no2.csv', index=False)