In [1]:
import pandas as pd
import numpy as np

# Read the data from the CSV file
df = pd.read_csv('./WB_sep_Hcho.csv')
df

,longitude,latitude,2023-09-01,2023-09-02,2023-09-03,2023-09-04,2023-09-05,2023-09-06,2023-09-07,2023-09-08,...,2023-09-21,2023-09-22,2023-09-23,2023-09-24,2023-09-25,2023-09-26,2023-09-27,2023-09-28,2023-09-29,2023-09-30
0,85.826363,21.539446,NaN,0.000151,0.000214,-0.000070,0.000223,NaN,0.000124,-0.000069,...,0.000063,0.000150,0.000188,0.000124,0.000130,0.000108,8.907208e-05,0.000154,0.000011,0.000307
1,85.826363,21.660331,NaN,NaN,0.000208,0.000220,0.000181,-0.000034,0.000010,0.000186,...,0.000252,0.000328,0.000105,0.000136,0.000090,0.000090,-3.887546e-05,0.000268,0.000210,0.000327
2,85.826363,21.781215,0.000110,NaN,NaN,NaN,0.000159,-0.000042,NaN,NaN,...,0.000547,0.000046,0.000107,0.000092,0.000127,0.000181,-3.432684e-05,0.000046,0.000221,-0.000011
3,85.826363,21.902100,0.000211,0.000089,0.000128,-0.000157,-0.000118,0.000589,0.000161,0.000024,...,0.000205,0.000256,0.000247,0.000030,0.000341,0.000215,3.695221e-04,0.000077,0.000162,0.000105
4,85.826363,22.022985,0.000123,-0.000024,NaN,0.000896,0.000244,NaN,NaN,0.000117,...,0.000177,0.000371,0.000328,0.000411,-0.000082,0.000065,2.044515e-04,0.000455,0.000294,0.000088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1627,89.786363,26.737492,NaN,0.000010,NaN,0.000032,NaN,NaN,-0.000020,0.001005,...,0.000173,0.000173,0.000234,0.000126,0.000120,-0.000037,-3.446093e-05,0.000086,0.000008,0.000342
1628,89.786363,26.858377,NaN,NaN,NaN,NaN,0.000080,NaN,0.000114,0.000293,...,0.000068,0.000159,NaN,0.000327,0.000188,-0.000001,2.537853e-05,0.000184,0.000137,0.000048
1629,89.786363,26.979262,0.000465,0.000199,-0.000007,0.000133,0.000138,0.000137,-0.000206,0.000252,...,0.000005,-0.000003,0.000087,0.000168,0.000195,0.000902,9.145046e-07,0.000080,0.000032,-0.000022
1630,89.786363,27.100146,NaN,0.000153,NaN,0.000100,0.000164,0.000105,NaN,0.000267,...,-0.000085,0.000319,0.000139,0.000380,0.000119,-0.000059,3.287576e-04,0.000055,-0.000008,0.000072
1631,89.786363,27.221031,NaN,0.000146,NaN,0.000185,NaN,0.000233,0.000377,0.000102,...,0.000335,0.000024,0.000071,-0.000018,0.000297,0.000034,9.335955e-05,0.000054,0.000090,0.000299

In [2]:
# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    print(f"Mean for {column}: {mean_value}")

Mean for 2023-09-01: 0.00017658423147917863
Mean for 2023-09-02: 7.952505485247068e-05
Mean for 2023-09-03: 6.927133235396383e-05
Mean for 2023-09-04: 0.00013657411532829638
Mean for 2023-09-05: 0.00012302181441437937
Mean for 2023-09-06: 0.0001818741282644733
Mean for 2023-09-07: 0.00011176978693448373
Mean for 2023-09-08: 0.0001358773893155415
Mean for 2023-09-09: 0.00014316677055605109
Mean for 2023-09-10: 0.00016428724793112896
Mean for 2023-09-11: 0.00012341724017399068
Mean for 2023-09-12: 0.00016850085720743674
Mean for 2023-09-13: 0.00012135318435474303
Mean for 2023-09-14: 0.00012731660712828117
Mean for 2023-09-15: 0.00014340078939701782
Mean for 2023-09-16: 0.00010009581368341528
Mean for 2023-09-17: 6.847244566964479e-05
Mean for 2023-09-18: 9.945379713425067e-05
Mean for 2023-09-19: 0.00014958907665407368
Mean for 2023-09-20: 0.000135263754334312
Mean for 2023-09-21: 0.0002054368962268077
Mean for 2023-09-22: 0.00012448127788121719
Mean for 2023-09-23: 0.00019689438805627066
Mean for 2023-09-24: 0.00014182730716339966
Mean for 2023-09-25: 0.00019105315903546812
Mean for 2023-09-26: 0.00016088956039432225
Mean for 2023-09-27: 8.141192612033656e-05
Mean for 2023-09-28: 0.00020220824235409597
Mean for 2023-09-29: 0.00016440441951914189
Mean for 2023-09-30: 0.0001692426503502316

In [3]:
import pandas as pd
import numpy as np

# Create a new DataFrame to store the results
result_df = pd.DataFrame(columns=['date', 'threshold_value'])

# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    result_df = pd.concat([result_df, pd.DataFrame({'date': [column], 'threshold_value': [mean_value]})], ignore_index=True)

# Print or display the resulting DataFrame
print(result_df)

          date  threshold_value
0   2023-09-01         0.000177
1   2023-09-02         0.000080
2   2023-09-03         0.000069
3   2023-09-04         0.000137
4   2023-09-05         0.000123
5   2023-09-06         0.000182
6   2023-09-07         0.000112
7   2023-09-08         0.000136
8   2023-09-09         0.000143
9   2023-09-10         0.000164
10  2023-09-11         0.000123
11  2023-09-12         0.000169
12  2023-09-13         0.000121
13  2023-09-14         0.000127
14  2023-09-15         0.000143
15  2023-09-16         0.000100
16  2023-09-17         0.000068
17  2023-09-18         0.000099
18  2023-09-19         0.000150
19  2023-09-20         0.000135
20  2023-09-21         0.000205
21  2023-09-22         0.000124
22  2023-09-23         0.000197
23  2023-09-24         0.000142
24  2023-09-25         0.000191
25  2023-09-26         0.000161
26  2023-09-27         0.000081
27  2023-09-28         0.000202
28  2023-09-29         0.000164
29  2023-09-30         0.000169

In [4]:
#thresold value csv file

In [5]:
# Save the resulting DataFrame to a CSV file
result_df.to_csv('./threshold_value_wb_sep_hcho.csv', index=False)