In [1]:
import pandas as pd
import numpy as np

# Read the data from the CSV file
df = pd.read_csv('/home/sysadm/Documents/Wb_o3/WB_sep_O3.csv')
df

,longitude,latitude,2023-09-01,2023-09-02,2023-09-03,2023-09-04,2023-09-05,2023-09-06,2023-09-07,2023-09-08,...,2023-09-20,2023-09-21,2023-09-22,2023-09-23,2023-09-24,2023-09-25,2023-09-26,2023-09-27,2023-09-28,2023-09-29
0,85.826363,21.539446,NaN,0.136622,0.124030,0.128609,0.128139,0.127809,0.136203,0.140493,...,0.116433,0.124778,0.115053,0.119522,0.130302,0.120607,0.122136,0.137705,0.119024,0.126997
1,85.826363,21.660331,NaN,NaN,0.123850,NaN,0.130576,0.128449,0.115164,0.139016,...,0.132266,0.123577,0.122390,0.115447,0.127622,0.130108,0.121094,0.135295,0.120905,0.137943
2,85.826363,21.781215,0.119590,NaN,0.122157,0.126527,0.127403,0.126119,0.131381,0.141127,...,0.132191,0.126507,0.119411,0.120017,0.125884,0.129418,0.123169,0.136052,0.119440,0.124917
3,85.826363,21.902100,0.122099,0.136620,0.126013,0.120409,0.132000,0.131614,0.137778,0.116278,...,0.127439,0.122679,0.116786,0.119549,0.128108,0.120606,0.120442,0.119038,0.116698,0.122688
4,85.826363,22.022985,0.123944,0.139371,0.121661,0.123362,0.127143,0.132549,0.133671,0.141058,...,0.123682,NaN,0.130133,0.123488,0.126920,0.119836,0.120365,0.127351,0.123969,0.139084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1627,89.786363,26.737492,NaN,0.139773,0.120074,0.120800,0.144528,0.140662,0.119232,0.116902,...,0.116567,0.131233,0.111215,0.124140,0.121596,0.120380,0.119616,0.123168,0.119277,0.125572
1628,89.786363,26.858377,NaN,NaN,0.140722,NaN,0.137333,0.140632,NaN,NaN,...,0.128919,0.131988,0.111167,NaN,0.137094,0.123399,0.122259,0.124927,0.122601,0.117637
1629,89.786363,26.979262,0.123394,0.135008,0.125009,NaN,0.132695,0.139845,0.122387,0.141548,...,0.115831,0.126593,0.119552,0.118133,0.122333,0.118827,0.119499,0.143026,0.120722,0.139250
1630,89.786363,27.100146,NaN,0.130122,0.122043,NaN,0.133452,0.141089,NaN,0.154343,...,0.130753,0.135256,0.115055,0.124444,0.132846,0.119744,0.133995,0.142723,0.123672,0.139833
1631,89.786363,27.221031,NaN,0.139692,0.118543,NaN,0.140510,0.140486,0.131710,0.158762,...,0.113651,0.125638,0.114338,0.125235,0.131417,0.126255,0.119913,0.126021,0.118807,0.119126

In [2]:
# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    print(f"Mean for {column}: {mean_value}")

Mean for 2023-09-01: 0.12232888929984144
Mean for 2023-09-02: 0.13810851226467227
Mean for 2023-09-03: 0.12633211459995297
Mean for 2023-09-04: 0.1254260786075398
Mean for 2023-09-05: 0.13153471672613043
Mean for 2023-09-06: 0.13230778803678195
Mean for 2023-09-07: 0.1311088094525799
Mean for 2023-09-08: 0.1368018109904657
Mean for 2023-09-09: 0.1188618854056437
Mean for 2023-09-10: 0.12208591896232943
Mean for 2023-09-11: 0.13405158949903967
Mean for 2023-09-12: 0.12916594060199393
Mean for 2023-09-13: 0.140378445902696
Mean for 2023-09-14: 0.11890652300303106
Mean for 2023-09-15: 0.1380485110732702
Mean for 2023-09-16: 0.12180760681915738
Mean for 2023-09-17: 0.12275397904104426
Mean for 2023-09-18: 0.1215782097354291
Mean for 2023-09-19: 0.12823230679882744
Mean for 2023-09-20: 0.11888366623562414
Mean for 2023-09-21: 0.12440473000846869
Mean for 2023-09-22: 0.12146210916079646
Mean for 2023-09-23: 0.12005726726190505
Mean for 2023-09-24: 0.12791032118255646
Mean for 2023-09-25: 0.12569937279950527
Mean for 2023-09-26: 0.12457056810683846
Mean for 2023-09-27: 0.13063637034950887
Mean for 2023-09-28: 0.12131741297424421
Mean for 2023-09-29: 0.12914325716905292

In [4]:
import pandas as pd
import numpy as np

# Create a new DataFrame to store the results
result_df = pd.DataFrame(columns=['date', 'threshold_value'])

# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    result_df = pd.concat([result_df, pd.DataFrame({'date': [column], 'threshold_value': [mean_value]})], ignore_index=True)

# Print or display the resulting DataFrame
print(result_df)

          date  threshold_value
0   2023-09-01         0.122329
1   2023-09-02         0.138109
2   2023-09-03         0.126332
3   2023-09-04         0.125426
4   2023-09-05         0.131535
5   2023-09-06         0.132308
6   2023-09-07         0.131109
7   2023-09-08         0.136802
8   2023-09-09         0.118862
9   2023-09-10         0.122086
10  2023-09-11         0.134052
11  2023-09-12         0.129166
12  2023-09-13         0.140378
13  2023-09-14         0.118907
14  2023-09-15         0.138049
15  2023-09-16         0.121808
16  2023-09-17         0.122754
17  2023-09-18         0.121578
18  2023-09-19         0.128232
19  2023-09-20         0.118884
20  2023-09-21         0.124405
21  2023-09-22         0.121462
22  2023-09-23         0.120057
23  2023-09-24         0.127910
24  2023-09-25         0.125699
25  2023-09-26         0.124571
26  2023-09-27         0.130636
27  2023-09-28         0.121317
28  2023-09-29         0.129143

In [5]:
#thresold value csv file

In [6]:
# Save the resulting DataFrame to a CSV file
result_df.to_csv('./threshold_value_wb_sep_o3.csv', index=False)