In [1]:
import pandas as pd
import numpy as np

# Read the data from the CSV file
df = pd.read_csv('/home/sysadm/Documents/Wb_no2/WB_sep_No2.csv')
df

,longitude,latitude,2023-09-01,2023-09-02,2023-09-03,2023-09-04,2023-09-05,2023-09-06,2023-09-07,2023-09-08,...,2023-09-20,2023-09-21,2023-09-22,2023-09-23,2023-09-24,2023-09-25,2023-09-27,2023-09-28,2023-09-29,2023-09-30
0,85.826363,21.539446,0.000025,0.000038,0.000031,0.000001,0.000025,0.000013,0.000009,-3.894893e-06,...,0.000027,-5.796801e-07,-8.314842e-07,0.000015,0.000024,0.000024,0.000009,-0.000004,NaN,0.000012
1,85.826363,21.660331,NaN,0.000042,0.000021,-0.000006,0.000010,0.000022,0.000023,-7.568676e-08,...,0.000009,4.803150e-05,1.894835e-06,0.000044,0.000023,0.000005,0.000015,0.000032,0.000020,0.000013
2,85.826363,21.781215,NaN,NaN,NaN,NaN,0.000009,0.000045,NaN,NaN,...,0.000018,-3.133270e-06,1.281026e-06,0.000010,0.000089,0.000013,-0.000003,-0.000006,0.000004,0.000006
3,85.826363,21.902100,0.000035,0.000016,0.000034,0.000001,0.000010,0.000027,0.000063,2.843120e-06,...,-0.000014,1.274635e-05,6.444148e-06,0.000013,0.000012,0.000025,0.000024,0.000009,0.000038,0.000034
4,85.826363,22.022985,0.000028,0.000003,NaN,-0.000004,0.000048,0.000008,NaN,9.569584e-07,...,0.000011,2.595606e-05,1.019999e-05,0.000029,0.000070,0.000020,0.000023,0.000007,0.000019,0.000018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1627,89.786363,26.737492,NaN,NaN,NaN,-0.000011,0.000016,0.000021,-0.000008,2.871382e-05,...,0.000024,1.740730e-05,6.000899e-06,0.000009,0.000002,0.000026,0.000006,0.000007,0.000020,0.000010
1628,89.786363,26.858377,0.000034,NaN,NaN,NaN,-0.000003,0.000026,0.000018,1.287261e-05,...,0.000012,2.849992e-05,5.405775e-06,NaN,0.000022,0.000020,0.000007,0.000018,0.000037,0.000029
1629,89.786363,26.979262,0.000013,0.000026,0.000017,-0.000002,NaN,0.000026,0.000003,1.419018e-05,...,0.000010,6.296583e-06,-2.365874e-06,0.000010,0.000002,0.000029,0.000013,0.000009,0.000025,0.000021
1630,89.786363,27.100146,NaN,0.000016,NaN,0.000020,0.000020,0.000023,NaN,4.840569e-06,...,0.000014,2.008240e-05,1.566046e-05,0.000006,0.000014,0.000021,0.000017,0.000029,0.000016,0.000020
1631,89.786363,27.221031,NaN,0.000007,NaN,0.000008,0.000020,0.000026,0.000005,1.647564e-05,...,NaN,3.342214e-05,-6.042989e-06,0.000018,0.000011,0.000011,0.000020,0.000008,0.000028,0.000021

In [2]:
# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    print(f"Mean for {column}: {mean_value}")

Mean for 2023-09-01: 1.5911777169029364e-05
Mean for 2023-09-02: 2.003883966237744e-05
Mean for 2023-09-03: 1.5767147452710835e-05
Mean for 2023-09-04: 5.5014398075150685e-06
Mean for 2023-09-05: 1.6973402525429324e-05
Mean for 2023-09-06: 2.0352760453039478e-05
Mean for 2023-09-07: 1.636912332566185e-05
Mean for 2023-09-08: 6.9746404960297965e-06
Mean for 2023-09-09: 5.549684121782148e-06
Mean for 2023-09-10: 1.7665101680875008e-05
Mean for 2023-09-11: 1.9864225357104375e-05
Mean for 2023-09-12: 1.3447150296507595e-05
Mean for 2023-09-13: 1.0093665462231342e-05
Mean for 2023-09-14: 1.478721950492948e-05
Mean for 2023-09-15: 1.992469665277174e-05
Mean for 2023-09-16: 1.4838730210742183e-05
Mean for 2023-09-17: 1.165039252803635e-05
Mean for 2023-09-18: 1.369284219033858e-05
Mean for 2023-09-19: 1.5208610007547183e-05
Mean for 2023-09-20: 1.5979494228223387e-05
Mean for 2023-09-21: 1.711488376264611e-05
Mean for 2023-09-22: 2.1425283215836033e-05
Mean for 2023-09-23: 1.670691535118237e-05
Mean for 2023-09-24: 1.685034014740315e-05
Mean for 2023-09-25: 1.7457169849576677e-05
Mean for 2023-09-27: 1.4602091715870152e-05
Mean for 2023-09-28: 1.8714575449944532e-05
Mean for 2023-09-29: 2.2879453071734893e-05
Mean for 2023-09-30: 1.835521195273031e-05

In [3]:
import pandas as pd
import numpy as np

# Create a new DataFrame to store the results
result_df = pd.DataFrame(columns=['date', 'threshold_value'])

# Iterate over each date column and calculate the mean, excluding NaN values
for column in df.columns[2:]:
    mean_value = np.nanmean(df[column])
    result_df = pd.concat([result_df, pd.DataFrame({'date': [column], 'threshold_value': [mean_value]})], ignore_index=True)

# Print or display the resulting DataFrame
print(result_df)

          date  threshold_value
0   2023-09-01         0.000016
1   2023-09-02         0.000020
2   2023-09-03         0.000016
3   2023-09-04         0.000006
4   2023-09-05         0.000017
5   2023-09-06         0.000020
6   2023-09-07         0.000016
7   2023-09-08         0.000007
8   2023-09-09         0.000006
9   2023-09-10         0.000018
10  2023-09-11         0.000020
11  2023-09-12         0.000013
12  2023-09-13         0.000010
13  2023-09-14         0.000015
14  2023-09-15         0.000020
15  2023-09-16         0.000015
16  2023-09-17         0.000012
17  2023-09-18         0.000014
18  2023-09-19         0.000015
19  2023-09-20         0.000016
20  2023-09-21         0.000017
21  2023-09-22         0.000021
22  2023-09-23         0.000017
23  2023-09-24         0.000017
24  2023-09-25         0.000017
25  2023-09-27         0.000015
26  2023-09-28         0.000019
27  2023-09-29         0.000023
28  2023-09-30         0.000018

In [4]:
#thresold value csv file

In [6]:
# Save the resulting DataFrame to a CSV file
result_df.to_csv('./threshold_value_wb_sep_no2.csv', index=False)